python:
  - 2.7
  - 3.4
os:
  - ubuntu/trusty64
cassandra:
  - dse-5.0
build:
  - script: |
      export JAVA_HOME=$CCM_JAVA_HOME
      export PATH=$JAVA_HOME/bin:$PATH
      # install master branch of driver.
      pushd ./
      echo "installing ccm"
      cd $HOME/ccm
      sudo python setup.py install
      cd $HOME
      git clone https://github.com/datastax/python-driver-dse.git
      cd python-driver-dse
      echo "installing python driver dse master"
      sudo python setup.py install
      export PYTHONPATH="${PYTHONPATH}:$HOME/python-driver-dse/tests"
      popd
      # Install dependencies
      echo "installing dse tinkerpop dependencies"
      sudo pip install -r test-requirements.txt
      sudo pip install nose-ignore-docstring
       echo "installing dse tinkerpop"
      sudo python setup.py install
      ECHO $PYTHONPATH
      echo "==========RUNNING DSE TESTS INTEGRATION TESTS=========="
      DSE_VERSION=$CCM_VERSION DSE_DRIVER_PERMIT_UNSUPPORTED_CORE=True ADS_HOME=$HOME/ nosetests -s -v --logging-format="[%(levelname)s] %(asctime)s %(thread)d: %(message)s" --with-ignore-docstrings --with-xunit --xunit-file=unit_results.xml tests/unit/ || true
      DSE_VERSION=$CCM_VERSION DSE_DRIVER_PERMIT_UNSUPPORTED_CORE=True ADS_HOME=$HOME/ nosetests -s -v --logging-format="[%(levelname)s] %(asctime)s %(thread)d: %(message)s" --with-ignore-docstrings --with-xunit --xunit-file=integration_results.xml tests/integration/ || true

  - xunit:
    - "*_results.xml"
