schedules:
  commit:
    schedule: per_commit
    branches:
      include: [master]
python:
  - 2.7
  - 3.4
os:
  - ubuntu/trusty64
cassandra:
  - dse-5.0
  - dse-5.1
build:
  - script: |
      export JAVA_HOME=$CCM_JAVA_HOME
      export PATH=$JAVA_HOME/bin:$PATH
      export CASS_DRIVER_NO_CYTHON=1
      # install master branch of driver.
      sudo apt-get install subversion
      pushd ./
      echo "installing ccm"
      cd $HOME/ccm
      sudo python setup.py install
      cd $HOME
      git clone git@github.com:riptano/python-dse-driver.git
      cd python-dse-driver
      echo "installing python dse driver master"
      sudo -E python setup.py install
      cd $HOME
      svn export https://github.com/aboudreault/tinkerpop/branches/dse-graph-tests/gremlin-python/src/main/jython
      cd jython
      echo "Installing custom tinkerpop build"
      sudo -E python setup.py install
      popd
      export PYTHONPATH="$HOME/python-dse-driver/"
      # Install dependencies
      echo "installing dse graph dependencies"
      sudo pip install -r test-requirements.txt
      sudo pip install nose-ignore-docstring
      echo "installing dse graph"
      sudo -E python setup.py install
      pwd
      echo "==========RUNNING DSE TESTS INTEGRATION TESTS=========="
      echo $PYTHONPATH
      CASSANDRA_DIR=$CCM_INSTALL_DIR DSE_VERSION=$CCM_VERSION nosetests -s -v --logging-format="[%(levelname)s] %(asctime)s %(thread)d: %(message)s" --with-ignore-docstrings --with-xunit --xunit-file=integration_results.xml graphtests/integration/ || true

  - xunit:
    - "*_results.xml"
